on:
  workflow_call:
    secrets:
      AZURE_CREDENTIALS:
        required: true
    
jobs:
  build-infrastructure:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Build Infrastructure
      run: az bicep build --file ./.infrastructure/main.bicep
    
    - name: Upload Infrastrcuture Artifact
      uses: actions/upload-artifact@v3
      with:
        name: infrastructure-artifact
        path: ./.infrastructure/