on:
  push:
  workflow_dispatch:

name: Build and Deploy
jobs:
  get-short-sha:
    runs-on: ubuntu-latest
    outputs:
      short_sha: ${{ steps.get-short-sha.outputs.short_sha }}
    steps:
    - run: |
       echo "short_sha=`git rev-parse --short HEAD`" >> $GITHUB_OUTPUT
      id: get-short-sha
 
  build-infrastructure:
    name: Build Infrastructure
    uses: ./.github/workflows/build-infrastructure.yaml
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
  
  build-and-push-container:
    name: Build and Push Container
    uses: ./.github/workflows/build-and-push-container.yaml
    needs: get-short-sha
    with:
      containerVersionTag: ${{ needs.get-short-sha.outputs.short_sha }}
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      REGISTRY_LOGIN_SERVER: ${{ secrets.REGISTRY_LOGIN_SERVER }}
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}

  deploy-infrastructure-development:
    name: Deploy Infrastructure to Development
    uses: ./.github/workflows/deploy-infrastructure.yaml
    needs: [build-infrastructure, get-short-sha]
    with:
      environment: development
      subscriptionId: ${{ vars.SUBSCRIPTION_ID }}
      resourceGroupName: ${{ vars.RESOURCE_GROUP_NAME }}
      containerVersionTag: ${{ needs.get-short-sha.outputs.short_sha }}
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
