on:
  workflow_call:
    inputs:
      containerVersionTag: 
        description: 'The container version tag to use.'
        required: true
        type: string
    secrets:
      AZURE_CREDENTIALS:
        required: true
      REGISTRY_LOGIN_SERVER:
        required: true
      REGISTRY_USERNAME:
        required: true
      REGISTRY_PASSWORD:
        required: true
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: echo version
      run: |
        echo "Here is the version: ${{ inputs.containerVersionTag }}"        
    
    - name: Build and Push Image
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - run: |
        docker build . -f BeerCollectionAPI/Dockerfile -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/beer-collection-api:${{ inputs.containerVersionTag }}
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/beer-collection-api:${{ inputs.containerVersionTag }}

    - run: |
        echo ${{ inputs.containerVersionTag }} >> ./container-version.txt

    - name: Publish Docker Version Artifact
      uses: actions/upload-artifact@v2
      with:
        name: container-version
        path: ./container-version.txt
    