on:
  workflow_call:
    inputs:
      environment:
        description: 'The environment to deploy to.'
        required: true
        type: string
      subscriptionId:
        description: 'The subscription to deploy to.'
        required: true
        type: string
      resourceGroupName:
        description: 'The resource group to deploy to.'
        required: true
        type: string
      containerVersionTag:
        description: 'The container version tag to use.'
        required: true
        type: string
    secrets:
      AZURE_CREDENTIALS:
        required: true

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      INFRASTRUCTURE_ARTIFACT_PATH: './infrastructure-artifact'
    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v3
      with:
        name: infrastructure-artifact
        path: ./infrastructure-artifact
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Infrastructure
      uses: azure/arm-deploy@v1
      with:
        resourceGroupName: ${{ inputs.resourceGroupName }}
        template: ./infrastructure-artifact/main.bicep
        parameters: ${{ format('{0}/parameters/{1}/parameters.json', env.INFRASTRUCTURE_ARTIFACT_PATH, inputs.environment) }} buildId=${{ github.run_id }} containerVersionTag=${{ inputs.containerVersionTag }}
        deploymentName: ${{ github.run_id }}
        subscriptionId: ${{ inputs.subscriptionId }}
